#!/usr/bin/env bash
# Generate ios/StuhiApp/Config.swift from the credentials kept outside the repo.
# Config.swift is gitignored — this is how a fresh clone gets its keys.
set -euo pipefail

ENV_FILE="${HOME}/.stuhi-app/env"
OUT="$(cd "$(dirname "$0")/.." && pwd)/ios/StuhiApp/Config.swift"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "error: $ENV_FILE not found." >&2
  echo "It holds the Supabase keys and is deliberately outside the repo." >&2
  exit 1
fi

# shellcheck disable=SC1090
source "$ENV_FILE"

: "${SUPABASE_URL:?missing in $ENV_FILE}"
: "${SUPABASE_PUBLISHABLE_KEY:?missing in $ENV_FILE}"

cat > "$OUT" <<EOF
import Foundation

// GENERATED by scripts/make-config.sh — do not edit, do not commit.
// Only the publishable key belongs in the app. The secret key stays in
// ~/.stuhi-app/env and is used by admin scripts only.

enum Config {
    static let supabaseURL = "${SUPABASE_URL}"
    static let supabasePublishableKey = "${SUPABASE_PUBLISHABLE_KEY}"
}
EOF

echo "wrote $OUT"
